#
# SPDX-License-Identifier: CC-BY-4.0
#

repository:
  name: fabric-docs-i18n
  description: Hyperledger Fabric is an enterprise-grade permissioned distributed
    ledger framework for developing solutions and applications. Its modular and
    versatile design satisfies a broad range of industry use cases. It offers
    a unique approach to consensus that enables performance at scale while preserving
    privacy.
  homepage: https://wiki.hyperledger.org/display/fabric
  default_branch: release-2.2
  has_downloads: false
  has_issues: true
  has_projects: true
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
